mariadb:
  build: ./mariadb
  expose:
    - "3306"
  volumes:
    - /var/lib/mysql:/var/lib/mysql

memcached:
  build: ./memcached
  expose:
    - "11211"

php-fpm:
  build: ./php-fpm
  expose:
    - "9000"
  links:
    - mariadb
  volumes:
    - /opt/www:/opt/www

nginx:
  build: ./nginx
  ports:
    - "80:80"
  links:
    - php-fpm
  volumes:
   - /opt/www:/opt/www
   - /etc/nginx:/etc/nginx

